{% set name = "authzed" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 48c6debdcbce2bfe897e2957addae86fe8f3697141615ec51e3cc8edbd878a18
  patches:
    - patches/0001-Apply-proper-version.patch

build:
  number: 0
  skip: true  # [py<39]

outputs:
  - name: {{ name }}
    script: build_base.sh  # [unix]
    script: build_base.bat # [win]
    requirements:
      host:
        - python
        - pip
        - uv-build >=0.8.15,<0.10.0
      run:
        - python
        - grpcio >=1.63,<2
        - protobuf >=5.26,<7
        - grpc-interceptor >=0.15.4,<0.16.0
        - googleapis-common-protos >=1.65.0,<2
        - protovalidate-python >=0.7.1,<1.1.0
    test:
      imports:
        - authzed.api.v0
        - authzed.api.materialize.v0
        - authzed.api.v1
        - authzed.api.v1alpha1
      requires:
        - pip
      commands:
        - pip check
        - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
        # Upstream tests require connection to local server, for which is not available:
        # "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to
        # connect to remote host: Connection refused"
  - name: {{ name }}-py
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - authzed.api.v0
        - authzed.api.materialize.v0
        - authzed.api.v1
        - authzed.api.v1alpha1
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://authzed.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Official SpiceDB client library for Python
  description: |
    Authzed is a database and service that stores, computes, and validates your
    application's permissions.
    Developers create a schema that models their permissions requirements and use
    a client library, such as this one, to apply the schema to the database, insert
    data into the database, and query the data to efficiently check permissions in
    their applications.
  dev_url: https://github.com/authzed/authzed-py
  doc_url: https://authzed.com/docs

extra:
  recipe-maintainers:
    - TS-ANC
